# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isPrime/isPrime.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15isPrime/isPrime.proto\x12\x07isPrime\"\x16\n\x05Value\x12\r\n\x05Value\x18\x01 \x01(\x03\"\"\n\x0fIsPrimeResponse\x12\x0f\n\x07IsPrime\x18\x01 \x01(\x08\x32G\n\x0bIsPrimeFunc\x12\x38\n\nCheckPrime\x12\x0e.isPrime.Value\x1a\x18.isPrime.IsPrimeResponse\"\x00\x42\x38Z6github.com/yoshiyuki-140/isprimenumber-gRPC-go/isPrimeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'isPrime.isPrime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/yoshiyuki-140/isprimenumber-gRPC-go/isPrime'
  _globals['_VALUE']._serialized_start=34
  _globals['_VALUE']._serialized_end=56
  _globals['_ISPRIMERESPONSE']._serialized_start=58
  _globals['_ISPRIMERESPONSE']._serialized_end=92
  _globals['_ISPRIMEFUNC']._serialized_start=94
  _globals['_ISPRIMEFUNC']._serialized_end=165
# @@protoc_insertion_point(module_scope)
