// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: isPrime/isPrime.proto

package isPrime

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// クライアントからサーバーへ送られるメッセージ
type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isPrime_isPrime_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_isPrime_isPrime_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_isPrime_isPrime_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// サーバーからクライアントへの返答
type IsPrimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsPrime bool `protobuf:"varint,1,opt,name=isPrime,proto3" json:"isPrime,omitempty"`
}

func (x *IsPrimeResponse) Reset() {
	*x = IsPrimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isPrime_isPrime_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsPrimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsPrimeResponse) ProtoMessage() {}

func (x *IsPrimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_isPrime_isPrime_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsPrimeResponse.ProtoReflect.Descriptor instead.
func (*IsPrimeResponse) Descriptor() ([]byte, []int) {
	return file_isPrime_isPrime_proto_rawDescGZIP(), []int{1}
}

func (x *IsPrimeResponse) GetIsPrime() bool {
	if x != nil {
		return x.IsPrime
	}
	return false
}

var File_isPrime_isPrime_proto protoreflect.FileDescriptor

var file_isPrime_isPrime_proto_rawDesc = []byte{
	0x0a, 0x15, 0x69, 0x73, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x2f, 0x69, 0x73, 0x50, 0x72, 0x69, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x69, 0x73, 0x50, 0x72, 0x69, 0x6d, 0x65,
	0x22, 0x1d, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x2b, 0x0a, 0x0f, 0x49, 0x73, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x32, 0x45, 0x0a, 0x0b,
	0x49, 0x73, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x12, 0x36, 0x0a, 0x0a, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x12, 0x0e, 0x2e, 0x69, 0x73, 0x50, 0x72,
	0x69, 0x6d, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x18, 0x2e, 0x69, 0x73, 0x50, 0x72,
	0x69, 0x6d, 0x65, 0x2e, 0x49, 0x73, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x79, 0x6f, 0x73, 0x68, 0x69, 0x79, 0x75, 0x6b, 0x69, 0x2d, 0x31, 0x34, 0x30, 0x2f,
	0x69, 0x73, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2d, 0x67, 0x52,
	0x50, 0x43, 0x2d, 0x67, 0x6f, 0x2f, 0x69, 0x73, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_isPrime_isPrime_proto_rawDescOnce sync.Once
	file_isPrime_isPrime_proto_rawDescData = file_isPrime_isPrime_proto_rawDesc
)

func file_isPrime_isPrime_proto_rawDescGZIP() []byte {
	file_isPrime_isPrime_proto_rawDescOnce.Do(func() {
		file_isPrime_isPrime_proto_rawDescData = protoimpl.X.CompressGZIP(file_isPrime_isPrime_proto_rawDescData)
	})
	return file_isPrime_isPrime_proto_rawDescData
}

var file_isPrime_isPrime_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_isPrime_isPrime_proto_goTypes = []any{
	(*Value)(nil),           // 0: isPrime.Value
	(*IsPrimeResponse)(nil), // 1: isPrime.IsPrimeResponse
}
var file_isPrime_isPrime_proto_depIdxs = []int32{
	0, // 0: isPrime.IsPrimeFunc.CheckPrime:input_type -> isPrime.Value
	1, // 1: isPrime.IsPrimeFunc.CheckPrime:output_type -> isPrime.IsPrimeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_isPrime_isPrime_proto_init() }
func file_isPrime_isPrime_proto_init() {
	if File_isPrime_isPrime_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_isPrime_isPrime_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_isPrime_isPrime_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*IsPrimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_isPrime_isPrime_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_isPrime_isPrime_proto_goTypes,
		DependencyIndexes: file_isPrime_isPrime_proto_depIdxs,
		MessageInfos:      file_isPrime_isPrime_proto_msgTypes,
	}.Build()
	File_isPrime_isPrime_proto = out.File
	file_isPrime_isPrime_proto_rawDesc = nil
	file_isPrime_isPrime_proto_goTypes = nil
	file_isPrime_isPrime_proto_depIdxs = nil
}
